RyanSUP/riffin-v2

src/components/TablatureInput/TablatureInput.js
src/pages/NewTablature/NewTablature.js
src/pages/TablatureEditor/TablatureEditor.js
src/services/tablatureServices.js

Improve tablature editor components.

Tablature editor refactor

---

src/App.js
src/components/Nav/Nav.js
src/components/SignupForm/SignupForm.js
src/components/TablatureCard/TablatureCard.js
src/pages/Profile/Profile.js
src/pages/TablatureEditorPLUS/TablatureEditorPLUS.js
src/pages/Trending/Trending.js
src/services/profileServices.js
src/services/tablatureServices.js

The profile and trending pages are up and (sort of) running. Users can view their own profile, view another profile (and see public tablature), and navigate to the trending page. Currently the trending page only logs public tablature to the console.
A big change necessary for this to work was adding the profile data to App.js' user state.

Stub profile and trending page functionality.

---

src/pages/TablatureEditorPLUS/TablatureEditorPLUS.js
src/services/profileServices.js
src/services/tablatureServices.js

The parameter names are more clear as to what data they're expecting.

Refactor fetch requests in the services folder.

---

.gitignore

adjust gitignore for env

---

src/components/TablatureCard/TablatureCardFooter.js

typo adjusted, sx -> xs, specific to MUI Grid
https://mui.com/material-ui/react-grid/

adjust dev tools error

---

src/components/TablatureCard/TablatureCardFooter.js
src/components/TrendingContent/TrendingContent.js

passed key prop to TablatureCard on TrendingContent component.

Tabcardkey

---

src/App.js
src/components/Nav/Nav.js
src/components/TablatureCard/TablatureCardFooter.js
src/components/TrendingContent/TrendingContent.js

adjust to prevent My Tab page from breaking if not logged in.

Newtabnonuser

---

src/App.js
src/components/Nav/Nav.js
src/components/TablatureCard/TablatureCardFooter.js
src/components/TrendingContent/TrendingContent.js

added user ternary to profile Route. Page broke prior if you weren't logged in.

Nonloggedinuser

---

src/App.js
src/components/Nav/Nav.js

removed from Route on app.js, applied to Nav.js

Profilerouteadjustment

---

src/App.js
src/components/TablatureCard/TablatureCardBody.js

Stub MUI grid layout in App.js with placeholders for Header, Content area, Nav, and Ad space.

Stub MUI grid layout in App.js

---

src/App.js
src/Theme.js

**Theme.js** file imported from prior project. Has not been refactored yet. 
**ThemeProvider** has been added to wrap the **App.js** rendered components. theme passed through.

Import theme file from prior MUI project

---

src/services/tablatureServices.js

The tablatureServices payload object did not match what the backend was expecting.

Fix CORS issues when creating and updating tablature

---

src/App.js
src/components/Card/Card.js
src/components/Card/Content.js
src/components/Card/Footer.js
src/components/Card/Header.js
src/components/Card/HeaderButtonGroup.js
src/components/Card/MetaData.js
src/components/ProfileContent/ProfileContent.js
src/components/TrendingContent/TrendingContent.js
src/pages/TablatureEditorPLUS/TablatureEditorPLUS.js

These changes focus on the Card component layout, though a bug fix for redirecting the user when saving a tablature snuck its way into the PR 😬
- Refactor card layout to match the figma document.
- Add placeholder tags to help visualize layout and theme. (They can be removed when tag functionality is in a good place)
- Refactor HeaderButtonGroup to use IconButton instead of Button components. This looks cleaner and fixes a bug where the Button is not responding to clicks.
- Expanding / collapsing a card now replaces the button with an appropriate icon.
- Fix the bug that redirects a user to the trending page after saving a new tablature.

Update the Card component layout

---

src/pages/Home/components/Header/HeaderLinks.js

add 'isLoggedInUser' property to LogOut button, add prop to avatar menu return in header links

Tim header links

---

src/App.js
src/Theme.js
src/components/Bar/Bar.js
src/index.js

Initial Nord Theme integration with this push. 
**darkTheme** has basic stubbing with room for expansion.
**lightTheme** is created but empty for later implementation. 
**FUTURE TOGGLE BUTTON INTEGRATION**
**Toggle Button** is stubbed up in the **App.js** along with the useState for setting the light mode. 
**ThemeProvider** will need to be adjusted to a ternary per the prior stack overflow document shared.
Button and useState are currently commented out, but kept so no additional coding is needed when ready to integrate/refactor.

initial nord theme integration

---

src/pages/Home/components/Editor/components/Controls/Controls.js

PrettierConfig the Controls.js file for uniformity

prettier format controls.js

---

src/pages/Home/components/RiffinEditor/EditorConfig.js
src/pages/Home/components/RiffinEditor/components/RiffinDrawer/RiffinDrawer.js
src/pages/Home/components/RiffinEditor/components/RiffinDrawer/components/Legend/Legend.js
src/pages/Home/components/RiffinEditor/components/TablatureBlock/components/InputTextarea/InputTextarea.js

The legend shows special keys and tablature notation. The key restriction has been removed as well, allowing the user to input any value they'd like. This is not that big of an issue since tabs are private.

Add legend to the editor drawer.

---

Todo.md
src/App.js
src/components/Card/components/DividerWrapper/DividerWrapper.js
src/components/Card/components/TagGroup/TagGroup.js
src/containers/TablatureProvider/TablatureProvider.js
src/pages/Home/components/ProfileContent/ProfileContent.js
src/pages/Home/components/TagBar/TagBar.js

This PR focuses on suggestions in the searchbar (TagBar). As a user types, the Autocomplete component provides the user with a list of suggestions based on tags they've used, their tablature names, and a preset list of Riffin Suggestions.

TagBar updates -- autocomplete suggestions

---

Todo.md
src/pages/Home/components/HeaderLinks/UserMenu/UserMenu.js
src/pages/Home/components/RiffinEditor/components/RiffinDrawer/RiffinDrawer.js
src/pages/Home/components/RiffinEditor/components/RiffinDrawer/components/SizeSlider/SizeSlider.js
src/pages/Home/components/RiffinEditor/components/RiffinDrawer/components/StaffMenuHeader/StaffMenuHeader.js

Fix #80. SizeSlider now checks if the slider is out of bounds before changing the size of the block.

---

src/components/Card/Card.js
src/components/Card/components/CopyToClipboardButton/CopyToClipboard.js
src/components/Card/components/EditTablatureButton/EditTablatureButton.js
src/components/Card/components/ExpandButton/ExpandButton.js

Resolve Issues #72 - users can copy tablature to their clipboard

---

src/pages/Home/components/ProfileContent/ProfileContent.js
src/pages/Home/components/ProfileContent/components/NoMatchesMessage.js
src/pages/Home/components/ProfileContent/components/NoTablatureMessage.js

A message will display if the user has no tablature, this message takes priority over the filter message. Filter message displays a 'no matches found' message when there are no filter results. resolve #88

Resolve #88 by implementing message components. 

---

package-lock.json
package.json
src/pages/Home/components/LoginSignupForm/components/LoginForm/LoginForm.js
src/pages/Home/components/LoginSignupForm/components/SignupForm/SignupForm.js

Add form validation and error feedback to log in / sign up forms!

---

src/containers/CognitoUserProvider/CognitoUserProvider.js
src/pages/Home/Home.js
src/pages/Home/components/HeaderLinks/HeaderLinks.js
src/pages/Home/components/LoginSignupForm/components/ChangePasswordForm.js/ChangePasswordForm.js
src/pages/Home/components/LoginSignupForm/components/LoginForm/LoginForm.js

User can change password

---

src/pages/Home/Home.js
src/pages/Home/components/Donate/Donate.js
src/pages/Home/components/RiffinEditor/RiffinProvider.js
src/pages/Home/components/RiffinEditor/components/SaveTabButton/SaveTabButton.js

Issues 103
